
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: TerraformTaskV2@2
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'infra_azure_connection'
    backendAzureRmResourceGroupName: 'vivind'
    backendAzureRmStorageAccountName: 'storagestgviv'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV2@2
  displayName: 'terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'infra_azure_connection'
- task: TerraformTaskV2@2
  displayName: 'terraform apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'infra_azure_connection'
# - task: TerraformTaskV2@2
#    displayName: 'terraform destroy'
#   inputs:
#     provider: 'azurerm'
#     command: 'destroy'
#     environmentServiceNameAzureRM: 'CSP-Dev-M&C(PRJ-6965)-Vivek Chaturvedi(3e357a00-39fc-400a-9d54-dcec7ed20bb4)'