# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo Hey this is my project piyu.
    echo See pniku singu
  displayName: 'Run new'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'CSP-Dev-M&C(PRJ-6965)-Vivek Chaturvedi(3e357a00-39fc-400a-9d54-dcec7ed20bb4)'
    backendAzureRmResourceGroupName: 'vivind'
    backendAzureRmStorageAccountName: 'storagestgviv'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'CSP-Dev-M&C(PRJ-6965)-Vivek Chaturvedi(1)(3e357a00-39fc-400a-9d54-dcec7ed20bb4)'

