

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV2@2
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'CSP-Dev-M&C(PRJ-6965)-Vivek Chaturvedi(3e357a00-39fc-400a-9d54-dcec7ed20bb4)'
    backendAzureRmResourceGroupName: 'vivind'
    backendAzureRmStorageAccountName: 'storagestgviv'
    backendAzureRmContainerName: 'statefile'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV2@2
  displayName: 'terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'CSP-Dev-M&C(PRJ-6965)-Vivek Chaturvedi(1)(3e357a00-39fc-400a-9d54-dcec7ed20bb4)'

